services:
  - type: web
    name: dermavision
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    python:
      version: 3.11
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
    plan: free  # Explicitly set to free tier
